version: 2
jobs:
    build_docs:
      docker:
         - image: circleci/python:3.6.8-stretch
      steps:
        - checkout
        - run:
            name: Set BASH_ENV
            command: |
              echo "set -e" >> $BASH_ENV;
              echo "export DISPLAY=:99" >> $BASH_ENV;
              echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV;
              echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;

        # Load our data
        - restore_cache:
            keys:
              - data-cache-0
              - pip-cache

        - run:
            name: Get conda running
            command: |
              wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
              chmod +x ~/miniconda.sh;
              ~/miniconda.sh -b -p ~/miniconda;
              echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;

        - run:
            name: Install dependencies in conda base environment
            command: |
              conda update -n base -c defaults conda
              pip install numpy scipy matplotlib nibabel
              pip install -U scikit-learn
              pip install --upgrade https://api.github.com/repos/mne-tools/mne-python/zipball/master
              git clone https://github.com/mne-tools/mne-bids.git --depth 1
              cd mne-bids
              pip install -e .
              cd ..


        - save_cache:
            key: pip-cache
            paths:
              - ~/.cache/pip

        # Look at what we have and fail early if there is some library conflict
        - run:
            name: Check installation
            command: |
               mne --version
               which python
               python -c "import mne; mne.sys_info()"

        # Run the scripts
        - run:
            name: Get data and run test
            command: |
               make test

        # Save the outputs
        - store_artifacts:
            path: doc/_build/html/
            destination: dev
        - store_artifacts:
            path: doc/_build/html_stable/
            destination: stable

        # Store the cache
        - save_cache:
            key: data-cache-0
            paths:
              - ~/mne_data/MNE-sample-data
              - ~/data


workflows:
  version: 2

  default:
    jobs:
      - build_docs
